# Generated by Django 4.0.1 on 2025-08-01 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='account_number',
        ),
    ]
