# Generated by Django 4.0.1 on 2025-08-01 01:40

from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userdata_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='account_number',
            field=models.CharField(blank=True, default=user.utils.create_new_ref_number, editable=False, max_length=10, unique=True),
        ),
    ]
