# Generated by Django 4.0.1 on 2025-08-01 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdata_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='username',
        ),
    ]
